// This file was generated by basehub. Do not edit directly. Read more: https://basehub.com/docs/api-reference/basehub-sdk

/* eslint-disable */
/* eslint-disable eslint-comments/no-restricted-disable */
/* tslint:disable */
// @ts-nocheck

export default {
    "scalars": [
        0,
        1,
        2,
        3,
        16,
        17,
        21,
        22,
        27,
        28,
        29,
        30,
        41,
        46,
        48,
        49
    ],
    "types": {
        "AnalyticsKeyScope": {},
        "BSHBEventSchema": {},
        "BSHBRichTextContentSchema": {},
        "BSHBRichTextTOCSchema": {},
        "BaseRichTextJson": {
            "blocks": [
                41
            ],
            "content": [
                2
            ],
            "toc": [
                3
            ],
            "__typename": [
                41
            ]
        },
        "BlockAudio": {
            "duration": [
                22
            ],
            "fileName": [
                41
            ],
            "fileSize": [
                29
            ],
            "lastModified": [
                22
            ],
            "mimeType": [
                41
            ],
            "url": [
                41
            ],
            "__typename": [
                41
            ]
        },
        "BlockCodeSnippet": {
            "allowedLanguages": [
                17
            ],
            "code": [
                41
            ],
            "html": [
                41,
                {
                    "theme": [
                        41
                    ]
                }
            ],
            "language": [
                17
            ],
            "__typename": [
                41
            ]
        },
        "BlockColor": {
            "b": [
                29
            ],
            "g": [
                29
            ],
            "hex": [
                41
            ],
            "hsl": [
                41
            ],
            "r": [
                29
            ],
            "rgb": [
                41
            ],
            "__typename": [
                41
            ]
        },
        "BlockDocument": {
            "_analyticsKey": [
                41,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_dashboardUrl": [
                41
            ],
            "_id": [
                41
            ],
            "_idPath": [
                41
            ],
            "_slug": [
                41
            ],
            "_slugPath": [
                41
            ],
            "_sys": [
                9
            ],
            "_title": [
                41
            ],
            "on_Glosario": [
                24
            ],
            "on_GlosarioItem": [
                25
            ],
            "on_glosarioItem_AsList": [
                51
            ],
            "__typename": [
                41
            ]
        },
        "BlockDocumentSys": {
            "apiNamePath": [
                41
            ],
            "createdAt": [
                41
            ],
            "hash": [
                41
            ],
            "id": [
                28
            ],
            "idPath": [
                41
            ],
            "lastModifiedAt": [
                41
            ],
            "slug": [
                41
            ],
            "slugPath": [
                41
            ],
            "title": [
                41
            ],
            "__typename": [
                41
            ]
        },
        "BlockFile": {
            "fileName": [
                41
            ],
            "fileSize": [
                29
            ],
            "lastModified": [
                22
            ],
            "mimeType": [
                41
            ],
            "url": [
                41
            ],
            "__typename": [
                41
            ]
        },
        "BlockImage": {
            "alt": [
                41
            ],
            "aspectRatio": [
                41
            ],
            "blurDataURL": [
                41
            ],
            "fileName": [
                41
            ],
            "fileSize": [
                29
            ],
            "height": [
                29
            ],
            "lastModified": [
                22
            ],
            "mimeType": [
                41
            ],
            "placeholderURL": [
                41
            ],
            "rawUrl": [
                41
            ],
            "thumbhash": [
                41
            ],
            "url": [
                41,
                {
                    "anim": [
                        41
                    ],
                    "background": [
                        41
                    ],
                    "blur": [
                        29
                    ],
                    "border": [
                        41
                    ],
                    "brightness": [
                        29
                    ],
                    "compression": [
                        41
                    ],
                    "contrast": [
                        29
                    ],
                    "dpr": [
                        29
                    ],
                    "fit": [
                        41
                    ],
                    "format": [
                        41
                    ],
                    "gamma": [
                        41
                    ],
                    "gravity": [
                        41
                    ],
                    "height": [
                        29
                    ],
                    "metadata": [
                        41
                    ],
                    "quality": [
                        29
                    ],
                    "rotate": [
                        41
                    ],
                    "sharpen": [
                        41
                    ],
                    "trim": [
                        41
                    ],
                    "width": [
                        29
                    ]
                }
            ],
            "width": [
                29
            ],
            "__typename": [
                41
            ]
        },
        "BlockList": {
            "_analyticsKey": [
                41,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_dashboardUrl": [
                41
            ],
            "_id": [
                41
            ],
            "_idPath": [
                41
            ],
            "_meta": [
                32
            ],
            "_searchKey": [
                41
            ],
            "_slug": [
                41
            ],
            "_slugPath": [
                41
            ],
            "_sys": [
                9
            ],
            "_title": [
                41
            ],
            "on_Glosario": [
                24
            ],
            "on_glosarioItem_AsList": [
                51
            ],
            "__typename": [
                41
            ]
        },
        "BlockOgImage": {
            "height": [
                29
            ],
            "url": [
                41
            ],
            "width": [
                29
            ],
            "__typename": [
                41
            ]
        },
        "BlockRichText": {
            "html": [
                41,
                {
                    "slugs": [
                        16
                    ],
                    "toc": [
                        16
                    ]
                }
            ],
            "json": [
                39
            ],
            "markdown": [
                41
            ],
            "plainText": [
                41
            ],
            "readingTime": [
                29,
                {
                    "wpm": [
                        29
                    ]
                }
            ],
            "on_Content": [
                18
            ],
            "__typename": [
                41
            ]
        },
        "BlockVideo": {
            "aspectRatio": [
                41
            ],
            "duration": [
                22
            ],
            "fileName": [
                41
            ],
            "fileSize": [
                29
            ],
            "height": [
                29
            ],
            "lastModified": [
                22
            ],
            "mimeType": [
                41
            ],
            "url": [
                41
            ],
            "width": [
                29
            ],
            "__typename": [
                41
            ]
        },
        "Boolean": {},
        "CodeSnippetLanguage": {},
        "Content": {
            "html": [
                41,
                {
                    "slugs": [
                        16
                    ],
                    "toc": [
                        16
                    ]
                }
            ],
            "json": [
                19
            ],
            "markdown": [
                41
            ],
            "plainText": [
                41
            ],
            "readingTime": [
                29,
                {
                    "wpm": [
                        29
                    ]
                }
            ],
            "__typename": [
                41
            ]
        },
        "ContentRichText": {
            "content": [
                2
            ],
            "toc": [
                3
            ],
            "__typename": [
                41
            ]
        },
        "DateFilter": {
            "eq": [
                21
            ],
            "isAfter": [
                21
            ],
            "isBefore": [
                21
            ],
            "isNull": [
                16
            ],
            "neq": [
                21
            ],
            "onOrAfter": [
                21
            ],
            "onOrBefore": [
                21
            ],
            "__typename": [
                41
            ]
        },
        "DateTime": {},
        "Float": {},
        "GetUploadSignedURL": {
            "signedURL": [
                41
            ],
            "uploadURL": [
                41
            ],
            "__typename": [
                41
            ]
        },
        "Glosario": {
            "_analyticsKey": [
                41,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_dashboardUrl": [
                41
            ],
            "_id": [
                41
            ],
            "_idPath": [
                41
            ],
            "_meta": [
                32
            ],
            "_searchKey": [
                41
            ],
            "_slug": [
                41
            ],
            "_slugPath": [
                41
            ],
            "_sys": [
                9
            ],
            "_title": [
                41
            ],
            "item": [
                25
            ],
            "items": [
                25
            ],
            "__typename": [
                41
            ]
        },
        "GlosarioItem": {
            "_analyticsKey": [
                41,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_dashboardUrl": [
                41
            ],
            "_id": [
                41
            ],
            "_idPath": [
                41
            ],
            "_slug": [
                41
            ],
            "_slugPath": [
                41
            ],
            "_sys": [
                9
            ],
            "_title": [
                41
            ],
            "content": [
                18
            ],
            "date": [
                41
            ],
            "icon": [
                41
            ],
            "slug": [
                41
            ],
            "__typename": [
                41
            ]
        },
        "GlosarioItemFilterInput": {
            "AND": [
                26
            ],
            "OR": [
                26
            ],
            "_id": [
                42
            ],
            "_slug": [
                42
            ],
            "_sys_apiNamePath": [
                42
            ],
            "_sys_createdAt": [
                20
            ],
            "_sys_hash": [
                42
            ],
            "_sys_id": [
                42
            ],
            "_sys_idPath": [
                42
            ],
            "_sys_lastModifiedAt": [
                20
            ],
            "_sys_slug": [
                42
            ],
            "_sys_slugPath": [
                42
            ],
            "_sys_title": [
                42
            ],
            "_title": [
                42
            ],
            "date": [
                20
            ],
            "icon": [
                42
            ],
            "slug": [
                42
            ],
            "__typename": [
                41
            ]
        },
        "GlosarioItemOrderByEnum": {},
        "ID": {},
        "Int": {},
        "JSON": {},
        "ListFilter": {
            "isEmpty": [
                16
            ],
            "length": [
                29
            ],
            "__typename": [
                41
            ]
        },
        "ListMeta": {
            "filteredCount": [
                29
            ],
            "totalCount": [
                29
            ],
            "__typename": [
                41
            ]
        },
        "MediaBlock": {
            "fileName": [
                41
            ],
            "fileSize": [
                29
            ],
            "lastModified": [
                22
            ],
            "mimeType": [
                41
            ],
            "url": [
                41
            ],
            "on_BlockAudio": [
                5
            ],
            "on_BlockFile": [
                10
            ],
            "on_BlockImage": [
                11
            ],
            "on_BlockVideo": [
                15
            ],
            "__typename": [
                41
            ]
        },
        "MediaBlockUnion": {
            "on_BlockAudio": [
                5
            ],
            "on_BlockFile": [
                10
            ],
            "on_BlockImage": [
                11
            ],
            "on_BlockVideo": [
                15
            ],
            "on_MediaBlock": [
                33
            ],
            "__typename": [
                41
            ]
        },
        "Mutation": {
            "getUploadSignedURL": [
                23,
                {
                    "fileHash": [
                        41
                    ],
                    "fileName": [
                        41,
                        "String!"
                    ]
                }
            ],
            "transaction": [
                45,
                {
                    "autoCommit": [
                        41
                    ],
                    "data": [
                        41,
                        "String!"
                    ],
                    "skipWorkflows": [
                        16
                    ],
                    "timeout": [
                        29
                    ]
                }
            ],
            "transactionAsync": [
                41,
                {
                    "autoCommit": [
                        41
                    ],
                    "data": [
                        41,
                        "String!"
                    ],
                    "skipWorkflows": [
                        16
                    ]
                }
            ],
            "transactionStatus": [
                45,
                {
                    "id": [
                        41,
                        "String!"
                    ]
                }
            ],
            "__typename": [
                41
            ]
        },
        "NumberFilter": {
            "eq": [
                22
            ],
            "gt": [
                22
            ],
            "gte": [
                22
            ],
            "isNull": [
                16
            ],
            "lt": [
                22
            ],
            "lte": [
                22
            ],
            "neq": [
                22
            ],
            "__typename": [
                41
            ]
        },
        "Query": {
            "_componentInstances": [
                50
            ],
            "_structure": [
                30,
                {
                    "format": [
                        49
                    ],
                    "resolveTargetsWith": [
                        48
                    ],
                    "targetBlock": [
                        44
                    ],
                    "withConstraints": [
                        16
                    ],
                    "withIDs": [
                        16
                    ],
                    "withTypeOptions": [
                        16
                    ]
                }
            ],
            "_sys": [
                38
            ],
            "glosario": [
                24,
                {
                    "filter": [
                        26
                    ],
                    "first": [
                        29
                    ],
                    "orderBy": [
                        27
                    ],
                    "skip": [
                        29
                    ]
                }
            ],
            "__typename": [
                41
            ]
        },
        "RepoSys": {
            "dashboardUrl": [
                41
            ],
            "forkUrl": [
                41
            ],
            "hash": [
                41
            ],
            "id": [
                28
            ],
            "slug": [
                41
            ],
            "title": [
                41
            ],
            "__typename": [
                41
            ]
        },
        "RichTextJson": {
            "content": [
                2
            ],
            "toc": [
                3
            ],
            "on_BaseRichTextJson": [
                4
            ],
            "on_ContentRichText": [
                19
            ],
            "__typename": [
                41
            ]
        },
        "SelectFilter": {
            "excludes": [
                41
            ],
            "excludesAll": [
                41
            ],
            "includes": [
                41
            ],
            "includesAll": [
                41
            ],
            "includesAny": [
                41
            ],
            "isEmpty": [
                16
            ],
            "__typename": [
                41
            ]
        },
        "String": {},
        "StringFilter": {
            "contains": [
                41
            ],
            "endsWith": [
                41
            ],
            "eq": [
                41
            ],
            "isNull": [
                16
            ],
            "matches": [
                43
            ],
            "notEq": [
                41
            ],
            "startsWith": [
                41
            ],
            "__typename": [
                41
            ]
        },
        "StringMatchesFilter": {
            "caseSensitive": [
                16
            ],
            "pattern": [
                41
            ],
            "__typename": [
                41
            ]
        },
        "TargetBlock": {
            "focus": [
                16
            ],
            "id": [
                41
            ],
            "label": [
                41
            ],
            "__typename": [
                41
            ]
        },
        "TransactionStatus": {
            "duration": [
                29
            ],
            "endedAt": [
                41
            ],
            "id": [
                41
            ],
            "message": [
                41
            ],
            "startedAt": [
                41
            ],
            "status": [
                46
            ],
            "__typename": [
                41
            ]
        },
        "TransactionStatusEnum": {},
        "Variant": {
            "apiName": [
                41
            ],
            "color": [
                41
            ],
            "id": [
                41
            ],
            "isDefault": [
                16
            ],
            "label": [
                41
            ],
            "__typename": [
                41
            ]
        },
        "_ResolveTargetsWithEnum": {},
        "_StructureFormatEnum": {},
        "_components": {
            "glosarioItem": [
                51,
                {
                    "filter": [
                        26
                    ],
                    "first": [
                        29
                    ],
                    "orderBy": [
                        27
                    ],
                    "skip": [
                        29
                    ]
                }
            ],
            "__typename": [
                41
            ]
        },
        "glosarioItem_AsList": {
            "_analyticsKey": [
                41,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_dashboardUrl": [
                41
            ],
            "_id": [
                41
            ],
            "_idPath": [
                41
            ],
            "_meta": [
                32
            ],
            "_searchKey": [
                41
            ],
            "_slug": [
                41
            ],
            "_slugPath": [
                41
            ],
            "_sys": [
                9
            ],
            "_title": [
                41
            ],
            "item": [
                25
            ],
            "items": [
                25
            ],
            "__typename": [
                41
            ]
        }
    }
}